# Generated by Django 3.1.4 on 2020-12-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entry_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.IntegerField(choices=[(2, 'TWO'), (3, 'THREE')], null=True),
        ),
    ]
