# Generated by Django 3.1.4 on 2020-12-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_auto_20201218_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
