# Generated by Django 3.1.4 on 2020-12-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_auto_20201218_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.CharField(choices=[('Two bed', 'TWO'), ('Three bed', 'THREE')], max_length=10, null=True),
        ),
    ]
