# Generated by Django 3.1.4 on 2020-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_auto_20201218_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
