# Generated by Django 3.1.4 on 2020-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_auto_20201218_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
